var namespacestd =
[
    [ "detail", "namespacestd_1_1detail.html", "namespacestd_1_1detail" ],
    [ "details", "namespacestd_1_1details.html", "namespacestd_1_1details" ],
    [ "mystd", "namespacestd_1_1mystd.html", "namespacestd_1_1mystd" ],
    [ "bool_constant", "structstd_1_1bool__constant.html", null ],
    [ "Cat_base", "structstd_1_1_cat__base.html", null ],
    [ "enable_if", "structstd_1_1enable__if.html", null ],
    [ "enable_if< true, T >", "structstd_1_1enable__if_3_01true_00_01_t_01_4.html", "structstd_1_1enable__if_3_01true_00_01_t_01_4" ],
    [ "integral_constant", "structstd_1_1integral__constant.html", "structstd_1_1integral__constant" ],
    [ "is_const", "structstd_1_1is__const.html", null ],
    [ "is_const< const T * >", "structstd_1_1is__const_3_01const_01_t_01_5_01_4.html", null ],
    [ "is_const< const volatile T * >", "structstd_1_1is__const_3_01const_01volatile_01_t_01_5_01_4.html", null ],
    [ "is_floating_point", "structstd_1_1is__floating__point.html", null ],
    [ "is_integral", "structstd_1_1is__integral.html", null ],
    [ "is_same", "structstd_1_1is__same.html", null ],
    [ "is_same< T, T >", "structstd_1_1is__same_3_01_t_00_01_t_01_4.html", null ],
    [ "is_signed", "structstd_1_1is__signed.html", null ],
    [ "is_unsigned", "structstd_1_1is__unsigned.html", null ],
    [ "remove_const", "structstd_1_1remove__const.html", "structstd_1_1remove__const" ],
    [ "remove_const< const T * >", "structstd_1_1remove__const_3_01const_01_t_01_5_01_4.html", "structstd_1_1remove__const_3_01const_01_t_01_5_01_4" ],
    [ "remove_const< const T >", "structstd_1_1remove__const_3_01const_01_t_01_4.html", "structstd_1_1remove__const_3_01const_01_t_01_4" ],
    [ "remove_const< const volatile T * >", "structstd_1_1remove__const_3_01const_01volatile_01_t_01_5_01_4.html", "structstd_1_1remove__const_3_01const_01volatile_01_t_01_5_01_4" ],
    [ "remove_const< const volatile T >", "structstd_1_1remove__const_3_01const_01volatile_01_t_01_4.html", "structstd_1_1remove__const_3_01const_01volatile_01_t_01_4" ],
    [ "remove_cv", "structstd_1_1remove__cv.html", "structstd_1_1remove__cv" ],
    [ "remove_reference", "structstd_1_1remove__reference.html", "structstd_1_1remove__reference" ],
    [ "remove_reference< T & >", "structstd_1_1remove__reference_3_01_t_01_6_01_4.html", "structstd_1_1remove__reference_3_01_t_01_6_01_4" ],
    [ "remove_volatile", "structstd_1_1remove__volatile.html", "structstd_1_1remove__volatile" ],
    [ "remove_volatile< volatile T * >", "structstd_1_1remove__volatile_3_01volatile_01_t_01_5_01_4.html", "structstd_1_1remove__volatile_3_01volatile_01_t_01_5_01_4" ],
    [ "remove_volatile< volatile T >", "structstd_1_1remove__volatile_3_01volatile_01_t_01_4.html", "structstd_1_1remove__volatile_3_01volatile_01_t_01_4" ]
];