#ifndef PHWIDGETS_SERVICE_TESTSUIT_H
#define PHWIDGETS_SERVICE_TESTSUIT_H

#ifndef DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
    #define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
    #include "./../doctest/doctest.h"
#endif // DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN


#endif // PHWIDGETS_SERVICE_TESTSUIT_H
