var _widget_8h =
[
    [ "Widget", "class_ph_widgets_1_1_widget.html", "class_ph_widgets_1_1_widget" ],
    [ "phwidgets_event", "class_ph_widgets_1_1_widget_1_1phwidgets__event.html", "class_ph_widgets_1_1_widget_1_1phwidgets__event" ],
    [ "ThisArgs", "struct_ph_widgets_1_1_widget_1_1_this_args.html", [
      [ "ArgArea", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_area.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_area" ],
      [ "ArgColor", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_color.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_color" ],
      [ "ArgDim", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_dim.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_dim" ],
      [ "ArgLong", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_long.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_long" ],
      [ "ArgPChar", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_char.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_char" ],
      [ "ArgPCursorDef", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_cursor_def.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_cursor_def" ],
      [ "ArgPGridLayoutData", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_grid_layout_data.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_grid_layout_data" ],
      [ "ArgPoint", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_point.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_point" ],
      [ "ArgPRowLayoutData", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_row_layout_data.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_row_layout_data" ],
      [ "ArgPVoid", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_void.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_void" ],
      [ "ArgRect", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_rect.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_rect" ],
      [ "ArgUnsigned", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_unsigned.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_unsigned" ],
      [ "ArgUnsignedLong", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_unsigned_long.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_unsigned_long" ],
      [ "ArgUnsignedShort", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_unsigned_short.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_unsigned_short" ]
    ] ],
    [ "ArgArea", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_area.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_area" ],
    [ "ArgUnsigned", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_unsigned.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_unsigned" ],
    [ "ArgUnsignedShort", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_unsigned_short.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_unsigned_short" ],
    [ "ArgUnsignedLong", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_unsigned_long.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_unsigned_long" ],
    [ "ArgLong", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_long.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_long" ],
    [ "ArgPChar", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_char.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_char" ],
    [ "ArgPVoid", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_void.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_void" ],
    [ "ArgRect", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_rect.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_rect" ],
    [ "ArgColor", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_color.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_color" ],
    [ "ArgPCursorDef", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_cursor_def.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_cursor_def" ],
    [ "ArgPGridLayoutData", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_grid_layout_data.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_grid_layout_data" ],
    [ "ArgPoint", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_point.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_point" ],
    [ "ArgPRowLayoutData", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_row_layout_data.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_p_row_layout_data" ],
    [ "ArgDim", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_dim.html", "struct_ph_widgets_1_1_widget_1_1_this_args_1_1_arg_dim" ],
    [ "ThisCallbacks", "struct_ph_widgets_1_1_widget_1_1_this_callbacks.html", [
      [ "Callback", "struct_ph_widgets_1_1_widget_1_1_this_callbacks_1_1_callback.html", "struct_ph_widgets_1_1_widget_1_1_this_callbacks_1_1_callback" ],
      [ "HotkeyCallback", "struct_ph_widgets_1_1_widget_1_1_this_callbacks_1_1_hotkey_callback.html", "struct_ph_widgets_1_1_widget_1_1_this_callbacks_1_1_hotkey_callback" ],
      [ "RawCallback", "struct_ph_widgets_1_1_widget_1_1_this_callbacks_1_1_raw_callback.html", "struct_ph_widgets_1_1_widget_1_1_this_callbacks_1_1_raw_callback" ]
    ] ],
    [ "RawCallback", "struct_ph_widgets_1_1_widget_1_1_this_callbacks_1_1_raw_callback.html", "struct_ph_widgets_1_1_widget_1_1_this_callbacks_1_1_raw_callback" ],
    [ "Callback", "struct_ph_widgets_1_1_widget_1_1_this_callbacks_1_1_callback.html", "struct_ph_widgets_1_1_widget_1_1_this_callbacks_1_1_callback" ],
    [ "HotkeyCallback", "struct_ph_widgets_1_1_widget_1_1_this_callbacks_1_1_hotkey_callback.html", "struct_ph_widgets_1_1_widget_1_1_this_callbacks_1_1_hotkey_callback" ],
    [ "ArgArea", "struct_ph_widgets_1_1_widget_1_1_arg_area.html", null ],
    [ "ArgUnsigned", "struct_ph_widgets_1_1_widget_1_1_arg_unsigned.html", null ],
    [ "ArgUnsignedShort", "struct_ph_widgets_1_1_widget_1_1_arg_unsigned_short.html", null ],
    [ "ArgUnsignedLong", "struct_ph_widgets_1_1_widget_1_1_arg_unsigned_long.html", null ],
    [ "ArgLong", "struct_ph_widgets_1_1_widget_1_1_arg_long.html", null ],
    [ "ArgPChar", "struct_ph_widgets_1_1_widget_1_1_arg_p_char.html", null ],
    [ "ArgPVoid", "struct_ph_widgets_1_1_widget_1_1_arg_p_void.html", null ],
    [ "ArgRect", "struct_ph_widgets_1_1_widget_1_1_arg_rect.html", null ],
    [ "ArgColor", "struct_ph_widgets_1_1_widget_1_1_arg_color.html", null ],
    [ "ArgPCursorDef", "struct_ph_widgets_1_1_widget_1_1_arg_p_cursor_def.html", null ],
    [ "ArgPGridLayoutData", "struct_ph_widgets_1_1_widget_1_1_arg_p_grid_layout_data.html", null ],
    [ "ArgPoint", "struct_ph_widgets_1_1_widget_1_1_arg_point.html", null ],
    [ "ArgPRowLayoutData", "struct_ph_widgets_1_1_widget_1_1_arg_p_row_layout_data.html", null ],
    [ "ArgDim", "struct_ph_widgets_1_1_widget_1_1_arg_dim.html", null ],
    [ "RawCallback", "struct_ph_widgets_1_1_widget_1_1_raw_callback.html", null ],
    [ "Callback", "struct_ph_widgets_1_1_widget_1_1_callback.html", null ],
    [ "HotkeyCallback", "struct_ph_widgets_1_1_widget_1_1_hotkey_callback.html", null ],
    [ "Arguments", "struct_ph_widgets_1_1_widget_1_1_arguments.html", null ],
    [ "Callbacks", "struct_ph_widgets_1_1_widget_1_1_callbacks.html", null ],
    [ "ArgumentsEx", "struct_ph_widgets_1_1_widget_1_1_arguments_ex.html", null ],
    [ "PhRect_t", "_widget_8h.html#ad0f5f2106375f06d35aa56702b029422", null ]
];