var annotated_dup =
[
    [ "PhWidgets", "namespace_ph_widgets.html", "namespace_ph_widgets" ],
    [ "ApInfo_t", "group__native.html#struct_ap_info__t", null ],
    [ "FontDescription", "group__native.html#struct_font_description", null ],
    [ "FontDetails", "group__native.html#struct_font_details", null ],
    [ "FontFilename", "group__native.html#struct_font_filename", null ],
    [ "FontName", "group__native.html#struct_font_name", null ],
    [ "PgAlpha_t", "group__native.html#struct_pg_alpha__t", null ],
    [ "PgColor_t", "group__native.html#struct_pg_color__t", null ],
    [ "PgGradient_t", "group__native.html#struct_pg_gradient__t", null ],
    [ "PgMap_t", "group__native.html#struct_pg_map__t", null ],
    [ "PgPattern_t", "group__native.html#struct_pg_pattern__t", null ],
    [ "PhArea_t", "group__native.html#struct_ph_area__t", null ],
    [ "PhCursorDef_t", "group__native.html#struct_ph_cursor_def__t", null ],
    [ "PhDim_t", "group__native.html#struct_ph_dim__t", null ],
    [ "PhEvent_t", "group__native.html#struct_ph_event__t", null ],
    [ "PhEventRegion_t", "group__native.html#struct_ph_event_region__t", null ],
    [ "PhImage_t", "group__native.html#struct_ph_image__t", null ],
    [ "PhPoint_t", "group__native.html#struct_ph_point__t", null ],
    [ "PhRect_t", "group__native.html#struct_ph_rect__t", null ],
    [ "PhRegionDataHdr_t", "group__native.html#struct_ph_region_data_hdr__t", null ],
    [ "PhRid_t", "group__native.html#struct_ph_rid__t", null ],
    [ "PtCallback_t", "group__native.html#struct_pt_callback__t", null ],
    [ "PtCallbackInfo_t", "group__native.html#struct_pt_callback_info__t", null ],
    [ "PtGridLayoutData_t", "group__native.html#struct_pt_grid_layout_data__t", null ],
    [ "PtHotkeyCallback_t", "group__native.html#struct_pt_hotkey_callback__t", null ],
    [ "PtRawCallback_t", "group__native.html#struct_pt_raw_callback__t", null ],
    [ "PtRowLayoutData_t", "group__native.html#struct_pt_row_layout_data__t", null ],
    [ "PtWidget_t", "group__native.html#struct_pt_widget__t", null ]
];