var group__native =
[
    [ "PtWidget_t", "struct_pt_widget__t.html", null ],
    [ "PhPoint_t", "struct_ph_point__t.html", null ],
    [ "PhDim_t", "struct_ph_dim__t.html", null ],
    [ "PhArea_t", "struct_ph_area__t.html", null ],
    [ "PhRegionDataHdr_t", "struct_ph_region_data_hdr__t.html", null ],
    [ "PhCursorDef_t", "struct_ph_cursor_def__t.html", null ],
    [ "PgColor_t", "struct_pg_color__t.html", null ],
    [ "PgPattern_t", "struct_pg_pattern__t.html", null ],
    [ "PtGridLayoutData_t", "struct_pt_grid_layout_data__t.html", null ],
    [ "PtRowLayoutData_t", "struct_pt_row_layout_data__t.html", null ],
    [ "PhRect_t", "struct_ph_rect__t.html", null ],
    [ "PtCallback_t", "struct_pt_callback__t.html", null ],
    [ "PtRawCallback_t", "struct_pt_raw_callback__t.html", null ],
    [ "PtHotkeyCallback_t", "struct_pt_hotkey_callback__t.html", null ],
    [ "PtCallbackInfo_t", "struct_pt_callback_info__t.html", null ],
    [ "PhEvent_t", "struct_ph_event__t.html", null ],
    [ "PhImage_t", "struct_ph_image__t.html", null ],
    [ "FontDetails", "struct_font_details.html", null ],
    [ "PhEventRegion_t", "struct_ph_event_region__t.html", null ],
    [ "PhRid_t", "struct_ph_rid__t.html", null ],
    [ "FontDescription", "struct_font_description.html", null ],
    [ "FontName", "struct_font_name.html", null ],
    [ "FontFilename", "struct_font_filename.html", null ],
    [ "PgAlpha_t", "struct_pg_alpha__t.html", null ],
    [ "PgMap_t", "struct_pg_map__t.html", null ],
    [ "PgGradient_t", "struct_pg_gradient__t.html", null ],
    [ "ApInfo_t", "struct_ap_info__t.html", null ]
];